apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "siab.fullname" . }}-config-master
  labels:
    {{- include "siab.labels" . | nindent 4 }}
    type: local
spec:
  storageClassName: {{ .Values.persistentvolume.master.config.storageclass }}
  capacity:
    storage: {{ .Values.persistentvolume.master.config.storage }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.persistentvolume.master.config.path }}