apiVersion: v1
kind: Service
metadata:
  name: {{ include "siab.fullname" . }}-master
  labels:
    {{- include "siab.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.master.type }}
  ports:
    - port: {{ .Values.service.master.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "siab.selectorLabels" . | nindent 4 }}
    role: master
